### ISSUE TITLE
stratum_var giving subscript out of bounds

### ISSUE THREAD

**Issue by KateMMiller** [USEPA/spsurvey#39]
When I try to generate a GRTS sample with a stratum_var specified, I get the following error: 

`Error in rslts[[i]] : subscript out of bounds`

Example, using NE_Lakes in spsurvey (and similar to an example in the help doc): 

`names(NE_Lakes)`
`grts(NE_Lakes, n_base = 10, stratum_var = "ELEV_CAT")`

**Comment by michaeldumelle** [comment]
@KateMMiller thanks for the inquiry. When selecting a stratified sample via `grts()`, you must explicitly specify each within-stratum sample size. For example, to select a sample from `NE_Lakes` where 25 observations are from the "low" elevation category and 15 observations are from the "high" elevation category, run

```
strata_n <- c(low = 10, high = 10)
strat_eqprob <- grts(NE_Lakes, n_base = strata_n, stratum_var = "ELEV_CAT")
strat_eqprob
#> Summary of Site Counts: 
#> 
#> siteuse by total: 
#>       Base
#> total   20
#> 
#> siteuse by stratum: 
#>      Base
#> high   10
#> low    10
```

More information can be found on our website by visiting the documentation page for `grts()` [linked here](https://usepa.github.io/spsurvey/reference/grts.html) or our "Spatially Balanced Sampling" vignette [linked here](https://usepa.github.io/spsurvey/articles/sampling.html).

In the next minor update to `spsurvey` we will consider either 1) returning a more informative error the message than the one you received or 2) recycling a length-one vector so that it applies to each stratum (e.g., the code you provided would select a sample of size 10 in each stratum).

I am going to close this issue now, but please reach out if you have any other questions!
